//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserVenue
    {
        public string ApplicationUser_Id { get; set; }
        public int Venue_VenueID { get; set; }
    }
}
